planning_pipelines:
  default_planning_pipeline: isaac_ros_cumotion
  pipeline_names:
    - isaac_ros_cumotion

isaac_ros_cumotion:
  planning_plugins:
    - isaac_ros_cumotion_moveit/CumotionPlanner
  request_adapters:
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/ResolveConstraintFrames
  start_state_max_bounds_error: 0.1
  num_steps: 32
